### ISSUE TITLE
Submodules without paths causing error when NPM installing via Git

### ISSUE THREAD

**Issue by Turbo87** [IonicaBizau/git-cloner#5]
I was trying to `npm install` this lib via Git instead of NPM itself and ran into this error:

```
npm ERR! Command failed: git submodule -q update --init --recursive
npm ERR! fatal: No url found for submodule path 'example/clones/a/bridge/to/1959' in .gitmodules
```

Is there any reason for having the submodules at all? Removing them seems to solve the issue.

**Comment by IonicaBizau** [comment]
Ah, whoups! That's a good point. 👍

The things in the `example/clones` directory should be ignored. Probably it works even by ignoring the `clones` directory itself.

**Comment by Turbo87** [comment]
yeah, ignoring the folder should work, but I think you will have to actively remove the folder before ignoring it so that git can pick that up.
